// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: can_message.proto

#include "can_message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace proto_test {
namespace example {
PROTOBUF_CONSTEXPR CanMessage::CanMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_payload_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CanMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CanMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CanMessageDefaultTypeInternal() {}
  union {
    CanMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CanMessageDefaultTypeInternal _CanMessage_default_instance_;
}  // namespace example
}  // namespace proto_test
static ::_pb::Metadata file_level_metadata_can_5fmessage_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_can_5fmessage_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_can_5fmessage_2eproto = nullptr;

const uint32_t TableStruct_can_5fmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::proto_test::example::CanMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::proto_test::example::CanMessage, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::proto_test::example::CanMessage, _impl_.message_payload_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::proto_test::example::CanMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::proto_test::example::_CanMessage_default_instance_._instance,
};

const char descriptor_table_protodef_can_5fmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021can_message.proto\022\022proto_test.example\""
  "\202\003\n\nCanMessage\022;\n\004type\030\001 \001(\0162-.proto_tes"
  "t.example.CanMessage.CanMessageType\022\027\n\017m"
  "essage_payload\030\002 \001(\014\"\235\002\n\016CanMessageType\022"
  "\013\n\007UNKNOWN\020\000\022\034\n\030GETCLAIMEDADDRESSREQUEST"
  "\020\001\022\035\n\031GETCLAIMEDADDRESSRESPONSE\020\002\022\035\n\031UDS"
  "OPENCOMMCHANNELREQUEST\020\004\022\036\n\032UDSOPENCOMMC"
  "HANNELRESPONSE\020\005\022\036\n\032UDSCLOSECOMMCHANNELR"
  "EQUEST\020\006\022\037\n\033UDSCLOSECOMMCHANNELRESPONSE\020"
  "\007\022\037\n\033READDATABYIDENTIFIERREQUEST\020\010\022 \n\034RE"
  "ADDATABYIDENTIFIERRESPONSE\020\nb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_can_5fmessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_can_5fmessage_2eproto = {
    false, false, 436, descriptor_table_protodef_can_5fmessage_2eproto,
    "can_message.proto",
    &descriptor_table_can_5fmessage_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_can_5fmessage_2eproto::offsets,
    file_level_metadata_can_5fmessage_2eproto, file_level_enum_descriptors_can_5fmessage_2eproto,
    file_level_service_descriptors_can_5fmessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_can_5fmessage_2eproto_getter() {
  return &descriptor_table_can_5fmessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_can_5fmessage_2eproto(&descriptor_table_can_5fmessage_2eproto);
namespace proto_test {
namespace example {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CanMessage_CanMessageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_can_5fmessage_2eproto);
  return file_level_enum_descriptors_can_5fmessage_2eproto[0];
}
bool CanMessage_CanMessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 10:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr CanMessage_CanMessageType CanMessage::UNKNOWN;
constexpr CanMessage_CanMessageType CanMessage::GETCLAIMEDADDRESSREQUEST;
constexpr CanMessage_CanMessageType CanMessage::GETCLAIMEDADDRESSRESPONSE;
constexpr CanMessage_CanMessageType CanMessage::UDSOPENCOMMCHANNELREQUEST;
constexpr CanMessage_CanMessageType CanMessage::UDSOPENCOMMCHANNELRESPONSE;
constexpr CanMessage_CanMessageType CanMessage::UDSCLOSECOMMCHANNELREQUEST;
constexpr CanMessage_CanMessageType CanMessage::UDSCLOSECOMMCHANNELRESPONSE;
constexpr CanMessage_CanMessageType CanMessage::READDATABYIDENTIFIERREQUEST;
constexpr CanMessage_CanMessageType CanMessage::READDATABYIDENTIFIERRESPONSE;
constexpr CanMessage_CanMessageType CanMessage::CanMessageType_MIN;
constexpr CanMessage_CanMessageType CanMessage::CanMessageType_MAX;
constexpr int CanMessage::CanMessageType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class CanMessage::_Internal {
 public:
};

CanMessage::CanMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:proto_test.example.CanMessage)
}
CanMessage::CanMessage(const CanMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CanMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_payload_){}
    , decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_payload().empty()) {
    _this->_impl_.message_payload_.Set(from._internal_message_payload(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.type_ = from._impl_.type_;
  // @@protoc_insertion_point(copy_constructor:proto_test.example.CanMessage)
}

inline void CanMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_payload_){}
    , decltype(_impl_.type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CanMessage::~CanMessage() {
  // @@protoc_insertion_point(destructor:proto_test.example.CanMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CanMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_payload_.Destroy();
}

void CanMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CanMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:proto_test.example.CanMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_payload_.ClearToEmpty();
  _impl_.type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CanMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .proto_test.example.CanMessage.CanMessageType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::proto_test::example::CanMessage_CanMessageType>(val));
        } else
          goto handle_unusual;
        continue;
      // bytes message_payload = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message_payload();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CanMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto_test.example.CanMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .proto_test.example.CanMessage.CanMessageType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // bytes message_payload = 2;
  if (!this->_internal_message_payload().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_message_payload(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto_test.example.CanMessage)
  return target;
}

size_t CanMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto_test.example.CanMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes message_payload = 2;
  if (!this->_internal_message_payload().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_message_payload());
  }

  // .proto_test.example.CanMessage.CanMessageType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CanMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CanMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CanMessage::GetClassData() const { return &_class_data_; }


void CanMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CanMessage*>(&to_msg);
  auto& from = static_cast<const CanMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto_test.example.CanMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message_payload().empty()) {
    _this->_internal_set_message_payload(from._internal_message_payload());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CanMessage::CopyFrom(const CanMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto_test.example.CanMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CanMessage::IsInitialized() const {
  return true;
}

void CanMessage::InternalSwap(CanMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_payload_, lhs_arena,
      &other->_impl_.message_payload_, rhs_arena
  );
  swap(_impl_.type_, other->_impl_.type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CanMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_can_5fmessage_2eproto_getter, &descriptor_table_can_5fmessage_2eproto_once,
      file_level_metadata_can_5fmessage_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace example
}  // namespace proto_test
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::proto_test::example::CanMessage*
Arena::CreateMaybeMessage< ::proto_test::example::CanMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::proto_test::example::CanMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
